# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '6a8843fd-7313-48e2-9381-3f9ef59ce82d'
  imageRepository: 'app1/app1nginx'
  containerRegistry: 'aksdevopsacr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
pool:
  vmImage: ubuntu-latest

resources:
- repo: self

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'acr-naidu'
    repository: 'release-version'
    command: 'buildAndPush'
    Dockerfile: $(dockerfilePath)
    displayName: "bulild and push docker image to ACR" 
- task: CmdLine@2
  inputs:
    script: 'echo Contents in System Default Working Directory; ls -R $(System.DefaultWorkingDirectory)'