trigger:
- main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '0e4b6d7e-7d2a-4800-acc4-eeba2495f737'
  imageRepository: 'ntest'
  containerRegistry: 'naiduregsistor.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'naiduregsistor42f5-auth'
  BUILD_NUMBER: $(Build.BuildId)
  ENVIRONMENT_NAME: 'DEV' # This should be set dynamically for different environments
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - upload: manifests
      artifact: manifests

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'naidu72azrelesepipeline.default'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            displayName: Deploy to Kubernetes cluster
            inputs:
              azureSubscription: 'az-sp-connection'
              scriptType: 'bash'
              scriptLocation: 'scriptPath'
              scriptPath: 'deploy.sh'
              arguments: '--build-number $(BUILD_NUMBER) --environment-name $(ENVIRONMENT_NAME)'
