# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'acr-naidu'
    repository: 'release-version'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    displayName: "bulild and push docker image to ACR" 
- task: CmdLine@2
  inputs:
    script: 'echo Contents in System Default Working Directory; ls -R $(System.DefaultWorkingDirectory)'