apiVersion : apps/v1
kind: Deployment
metadata:
  name: myapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp 
    spec:
      containers:
        - name: myapp 
          image: naiduregsistor.azurecr.io/myapp
          ports:
          - containerPort: 8080
          env:
            - name: BUILD_NUMBER
              value: "$(BUILD_NUMBER)"